baseURL = "https://6TPI/Sponsor-et-E-sport/"
languageCode = 'fr-fr'
title = 'E-Sport Sponsor'
theme = 'blowfish'

[params]
  logo = "/img/fight.png"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableFingerprinting = true
  disableSRI = true


[params.homepage]
  layout = "background"              # type de home : hero
  homepageImage = "img/background.svg"  # image dans assets/img
  showRecent = true
  showRecentItems = 6

  